### ISSUE TITLE
missing documentation for pyaid installation

### ISSUE THREAD

**Issue by martinResearch** [sernst/Nimble#3]
Hi, 

I get an error a the line " import pyaid" in __init__.py.
What is PyAid and how do we install it ? 
I could not find it on google or PyPI

**Comment by sernst** [comment]
Hello Martin,

PyAid is another package I created that supports Nimble and other related packages: 

https://github.com/sernst/PyAid

It's not packaged as a pypi package because at the time of original development, managing Python packages in the Maya Python environment wasn't easily amenable to pip package installation. Instead, these packages were intended to be downloaded into a common folder that was included as an extra Python path in the Maya env file as well as added to the `PYTHONPATH` of any remote Python interpreters that would interact via Nimble with Maya.

**Comment by sernst** [comment]
I've added documentation to the README.md with this additional information. Thanks for surfacing that missing info.
